# References:
# https://github.com/conda-forge/staged-recipes/blob/main/recipes/example
# https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-builds
#
# The example above suggests that one use SPDX identifies for the
# license field but this is not yet supported by conda build or conda-verfity;
# see https://github.com/conda/conda/issues/5280
# This project uses the SPDX identifier GPL-3.0-or-later; see
# https://spdx.org/licenses/GPL-3.0-or-later.html
#
# Warnings when in recipes we execute: conda build xrst
# 1. main_build.py:520: FutureWarning: The default `pkg_format` of '.tar.bz2'
#    is deprecated and will be removed in 25.1.
# 2. No numpy version specified in conda_build_config.yaml.
#    Falling back to default numpy value of 1.22.
#    (We have not specified a conda_build_config.yaml file for this project.)
#
# Warnings when in recipes we execute: conda verify xrst
# 1. WARNING: Setting build platform.  ...
#    (We are not setting a specific build platform.)
# 2. WARNING: Setting build arch. ...
#    (We are not setting noarch and not a specific build arch.)
# 3. C2122 Found invalid license family "GPL-3.0-or-later"
#    (See the comments above about SPDX identifiers.)
#

{% set name = "xrst" %}
{% set version = "2025.0.4" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xrst-{{ version }}.tar.gz
  sha256: 2f75155177c1c70ae0da81c0a0d68a0192be77bb36acc948e8310f587c50a09b

build:
  entry_points:
    - xrst = xrst:run_xrst
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - sphinx
    - toml
    - sphinx-copybutton
    - pyspellchecker
    - furo

test:
  imports:
    - xrst
  commands:
    - pip check
    - xrst --help
  requires:
    - python {{ python_min }}
    - importlib_resources
    - typing-extensions
    - pip

about:
  home: https://github.com/bradbell/xrst
  summary: Extract RST files from source code and run Sphinx
  license: GPL-3.0-or-later
  license_file: gpl-3.0.txt
  doc_url: https://xrst.readthedocs.io/latest/

extra:
  recipe-maintainers:
    - bradbell
